version: "3"

services:
    message-broker:
        image: redis:latest
        container_name: message-broker
        ports:
            - "6379:6379"
        volumes:
            - message-broker-data:/data
        networks:
            - imagewiz

    task-queue:
        image: hibiken/asynqmon:latest
        container_name: task-queue
        environment:
            - REDIS_ADDR=message-broker:6379
        ports:
            - "8080:8080"
        depends_on:
            - message-broker
        networks:
            - imagewiz

networks:
    imagewiz:

volumes:
    message-broker-data:
