version: "3"

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - imagewiz

    task-queue:
        image: hibiken/asynqmon:latest
        container_name: task-queue
        environment:
            - REDIS_ADDR=redis:6379
        ports:
            - "8080:8080"
        depends_on:
            - redis
        networks:
            - imagewiz

networks:
    imagewiz:

volumes:
    redis-data:
